name: Robot Repo Submission
description: Submit a robot repository.
title: "robot-showcase-request"
labels:
  - robot-repo
body:
  - type: markdown
    attributes:
      value: |
        Please keep the default issue title: **robot-showcase-request**
  - type: input
    id: repo
    attributes:
      label: GitHub repo URL
      description: Must include both owner and repo (not just the org).
      placeholder: https://github.com/TheRobotStudio/SO-ARM100
    validations:
      required: true
  - type: input
    id: org
    attributes:
      label: Author / Company / Lab (optional)
      placeholder: The Robot Studio
  - type: input
    id: author_site
    attributes:
      label: Author website (optional)
      placeholder: https://www.therobotstudio.com/
  - type: input
    id: author_x
    attributes:
      label: Author X/Twitter (optional)
      placeholder: https://x.com/yourhandle
  - type: input
    id: author_linkedin
    attributes:
      label: Author LinkedIn (optional)
      placeholder: https://www.linkedin.com/company/yourcompany
  - type: input
    id: author_github
    attributes:
      label: Author GitHub (optional)
      placeholder: https://github.com/yourorg
  - type: textarea
    id: summary
    attributes:
      label: Short summary
      placeholder: LeRobot-compatible SO-ARM100 with gripper.
  - type: input
    id: demo
    attributes:
      label: Demo URL (optional)
      placeholder: https://huggingface.co/spaces/your-demo
  - type: input
    id: tags
    attributes:
      label: Tags (optional)
      placeholder: LeRobotCompatible, HuggingFace, Arm, Gripper
  - type: textarea
    id: hf_datasets
    attributes:
      label: Hugging Face datasets (one per line, optional)
      description: Paste one link per line.
      placeholder: |-
        https://huggingface.co/datasets/your-dataset
        https://huggingface.co/datasets/your-other-dataset
  - type: textarea
    id: robots
    attributes:
      label: Robot mapping (optional)
      description: Use "RobotName — file.urdf" (filename only; no path). If omitted, we use the .urdf filename as the robot name.
      placeholder: |-
        SO-ARM100 — so100.urdf
        SO-ARM101 — so101_new_calib.urdf
  - type: input
    id: contact
    attributes:
      label: Contact (optional)
  - type: textarea
    id: extra
    attributes:
      label: Extra links or notes (optional)
