name: Robot Repo Submission
description: Submit a robot repository.
title: "[Robot Repo]"
labels:
  - robot-repo
body:
  - type: input
    id: repo
    attributes:
      label: GitHub repo URL
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Robot / project name (optional)
  - type: input
    id: org
    attributes:
      label: Author / Company / Lab (optional)
  - type: textarea
    id: summary
    attributes:
      label: Short summary
  - type: input
    id: demo
    attributes:
      label: Demo URL (optional)
  - type: input
    id: tags
    attributes:
      label: Tags (optional)
  - type: textarea
    id: robots
    attributes:
      label: Robots (optional)
  - type: input
    id: contact
    attributes:
      label: Contact (optional)
  - type: textarea
    id: extra
    attributes:
      label: Extra links or notes (optional)
